[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "haseforge"
version = "0.1.1"
description = "Robot arm control framework with web server and GPIO control"
authors = [{ name = "Catrick-cpu" }]
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask",
    "colorama",
    "pyfiglet"
]

[project.urls]
Homepage = "https://github.com/catrick-cpu/haseforge"